# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on: [push, pull_request]

jobs:

  test_net462:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore Anixe.Ion.sln

      - name: Build Solution
        run: |
          msbuild.exe Anixe.Ion.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Run Tests
        run: vstest.console.exe .\Anixe.Ion.UnitTests\bin\Release\net462\Anixe.Ion.UnitTests.dll
        
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            8.0.x
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal